# Generated by Django 5.2.2 on 2025-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fame', '0001_initial'),
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworkusers',
            name='communities',
            field=models.ManyToManyField(related_name='in_community', to='fame.expertiseareas'),
        ),
    ]
